name: CI mit Trivy Security Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Docker Image bauen
        run: docker build -t flask-secure-app .

      - name: Sicherheits-Scan mit Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: flask-secure-app
